In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('GMClean_data.csv')
data

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (2,101,102,103,104,105,106,153,185,186,187,188,189,190) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,Tiempo,AGEB,GRAPROES,GRAPROES_F,GRAPROES_M,HOGJEF_F,HOGJEF_M,LOC,MUN,...,VPH_SNBIEN,VPH_S_ELEC,VPH_TELEF,VPH_TV,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M
0,2,2010,0012,8.37,8.13,8.63,231,847,1,5,...,5,0,625,1050,NaN,NaN,NaN,NaN,NaN,NaN
1,3,2010,0012,8.92,8.67,9.22,6,37,1,5,...,0,0,28,40,NaN,NaN,NaN,NaN,NaN,NaN
2,4,2010,0012,8.83,8.49,9.16,7,37,1,5,...,0,0,23,41,NaN,NaN,NaN,NaN,NaN,NaN
3,5,2010,0012,8.77,8.78,8.76,6,34,1,5,...,0,0,21,39,NaN,NaN,NaN,NaN,NaN,NaN
4,6,2010,0012,8.02,7.75,8.37,10,24,1,5,...,*,0,23,32,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16573,17248,2020,3445,9.07,9.38,8.67,5,11,1,5,...,0,0,8,16,47,26,21,6,3,3
16574,17249,2020,3445,8.35,8.23,8.49,8,26,1,5,...,0,0,17,29,111,56,55,0,0,0
16575,17250,2020,3445,9.41,9.88,9,4,*,1,5,...,0,0,4,6,21,11,10,*,*,0
16576,17251,2020,3445,9.3,9.67,8.91,4,5,1,5,...,0,0,5,8,28,15,13,0,0,0
16577,17252,2020,3445,8.97,8.86,9.05,8,17,1,5,...,0,0,11,25,75,32,43,6,3,3

In [3]:
chosen_df = data[['Tiempo','NOM_ENT', 'MUN', 'LOC', 'AGEB', 'MZA', 'POBTOT', 'P_0A2', 'P_60YMAS', 'PROM_HNV', 'GRAPROES', 
                  'GRAPROES_F', 'POCUPADA', 'POCUPADA_F', 'PDER_SS', 'VIVTOT', 'TVIVHAB', 'TVIVPAR', 'VIVPAR_HAB', 
                  'VIVPAR_UT', 'PROM_OCUP', 'VPH_2YMASD', 'VPH_AUTOM', 'VPH_PC', 'VPH_INTER']]
chosen_df.head()

,Tiempo,NOM_ENT,MUN,LOC,AGEB,MZA,POBTOT,P_0A2,P_60YMAS,PROM_HNV,...,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPAR_UT,PROM_OCUP,VPH_2YMASD,VPH_AUTOM,VPH_PC,VPH_INTER
0,2010,Distrito Federal,5,1,0012,0,4312,212,370,2.26,...,1124,1083,1119,1078,5,3.99,598,314,284,182
1,2010,Distrito Federal,5,1,0012,1,174,9,13,2.12,...,43,*,*,*,*,4.05,26,15,12,6
2,2010,Distrito Federal,5,1,0012,2,167,5,13,1.82,...,44,*,*,*,*,3.80,23,12,7,5
3,2010,Distrito Federal,5,1,0012,3,153,8,9,2,...,40,*,*,*,*,3.83,21,17,13,11
4,2010,Distrito Federal,5,1,0012,4,128,7,12,2.47,...,35,*,*,*,*,3.76,19,8,8,6

In [4]:
steps = chosen_df.replace(to_replace='*', value='') # replacing '*' with ''
steps = steps.replace(to_replace='N/D', value='') # replacing 'N/D' with ''
steps.columns= steps.columns.str.lower() # change column names to lower case

steps.head()

,tiempo,nom_ent,mun,loc,ageb,mza,pobtot,p_0a2,p_60ymas,prom_hnv,...,vivtot,tvivhab,tvivpar,vivpar_hab,vivpar_ut,prom_ocup,vph_2ymasd,vph_autom,vph_pc,vph_inter
0,2010,Distrito Federal,5,1,0012,0,4312,212,370,2.26,...,1124,1083,1119,1078,5,3.99,598,314,284,182
1,2010,Distrito Federal,5,1,0012,1,174,9,13,2.12,...,43,,,,,4.05,26,15,12,6
2,2010,Distrito Federal,5,1,0012,2,167,5,13,1.82,...,44,,,,,3.80,23,12,7,5
3,2010,Distrito Federal,5,1,0012,3,153,8,9,2,...,40,,,,,3.83,21,17,13,11
4,2010,Distrito Federal,5,1,0012,4,128,7,12,2.47,...,35,,,,,3.76,19,8,8,6

In [5]:
steps.dtypes

tiempo         int64
nom_ent       object
mun            int64
loc            int64
ageb          object
mza            int64
pobtot         int64
p_0a2         object
p_60ymas      object
prom_hnv      object
graproes      object
graproes_f    object
pocupada      object
pocupada_f    object
pder_ss       object
vivtot         int64
tvivhab       object
tvivpar       object
vivpar_hab    object
vivpar_ut     object
prom_ocup     object
vph_2ymasd    object
vph_autom     object
vph_pc        object
vph_inter     object
dtype: object

In [6]:
cols=[i for i in steps.columns if i not in ["nom_ent","ageb"]] # change data frame dtypes to do math
for col in cols:
    steps[col]=pd.to_numeric(steps[col])

steps.dtypes

tiempo          int64
nom_ent        object
mun             int64
loc             int64
ageb           object
mza             int64
pobtot          int64
p_0a2         float64
p_60ymas      float64
prom_hnv      float64
graproes      float64
graproes_f    float64
pocupada      float64
pocupada_f    float64
pder_ss       float64
vivtot          int64
tvivhab       float64
tvivpar       float64
vivpar_hab    float64
vivpar_ut     float64
prom_ocup     float64
vph_2ymasd    float64
vph_autom     float64
vph_pc        float64
vph_inter     float64
dtype: object

In [8]:
pd.options.display.max_columns = None # to show all columns
pd.options.display.max_rows = None

steps.head()

,tiempo,nom_ent,mun,loc,ageb,mza,pobtot,p_0a2,p_60ymas,prom_hnv,graproes,graproes_f,pocupada,pocupada_f,pder_ss,vivtot,tvivhab,tvivpar,vivpar_hab,vivpar_ut,prom_ocup,vph_2ymasd,vph_autom,vph_pc,vph_inter
0,2010,Distrito Federal,5,1,0012,0,4312,212.0,370.0,2.26,8.37,8.13,1658.0,537.0,3214.0,1124,1083.0,1119.0,1078.0,5.0,3.99,598.0,314.0,284.0,182.0
1,2010,Distrito Federal,5,1,0012,1,174,9.0,13.0,2.12,8.92,8.67,67.0,23.0,128.0,43,NaN,NaN,NaN,NaN,4.05,26.0,15.0,12.0,6.0
2,2010,Distrito Federal,5,1,0012,2,167,5.0,13.0,1.82,8.83,8.49,66.0,20.0,105.0,44,NaN,NaN,NaN,NaN,3.80,23.0,12.0,7.0,5.0
3,2010,Distrito Federal,5,1,0012,3,153,8.0,9.0,2.00,8.77,8.78,60.0,19.0,119.0,40,NaN,NaN,NaN,NaN,3.83,21.0,17.0,13.0,11.0
4,2010,Distrito Federal,5,1,0012,4,128,7.0,12.0,2.47,8.02,7.75,47.0,18.0,101.0,35,NaN,NaN,NaN,NaN,3.76,19.0,8.0,8.0,6.0

In [9]:
# Percents 

pop02_pct = steps['p_0a2']/steps['pobtot']*100

steps['pct_0a2'] = pop02_pct

pop60_pct = steps['p_60ymas']/steps['pobtot']*100
steps['pct_60'] = pop60_pct

working_fem_pct = steps['pocupada_f']/steps['pocupada']*100

steps['pct_wf'] = working_fem_pct

inhabited_hh_pct = steps['tvivhab']/steps['vivtot']*100
steps['pct_t_inhab_hh'] = inhabited_hh_pct

private_hh_pct = steps['tvivpar']/steps['vivtot']*100
steps['pct_privhh'] = private_hh_pct

inhabited_pvt_hh_pct = steps['vivpar_hab']/steps['tvivhab']*100
steps['pct_privhh_inhab'] = inhabited_pvt_hh_pct

temp_pvt_hh_pct = steps['vivpar_ut']/steps['vivtot']*100
steps['pct_hhtemp'] = temp_pvt_hh_pct

hh_with_car = steps['vph_autom']/steps['tvivhab']*100
steps['pct_hh_car'] = hh_with_car

hh_with_pc = steps['vph_pc']/steps['tvivhab']*100
steps['pct_hh_pc'] = hh_with_pc

hh_with_int = steps['vph_inter']/steps['tvivhab']*100
steps['pct_hh_int'] = hh_with_int

shiny_df = steps
shiny_df.head()

,tiempo,nom_ent,mun,loc,ageb,mza,pobtot,p_0a2,p_60ymas,prom_hnv,graproes,graproes_f,pocupada,pocupada_f,pder_ss,vivtot,tvivhab,tvivpar,vivpar_hab,vivpar_ut,prom_ocup,vph_2ymasd,vph_autom,vph_pc,vph_inter,pct_0a2,pct_60,pct_wf,pct_t_inhab_hh,pct_privhh,pct_privhh_inhab,pct_hhtemp,pct_hh_car,pct_hh_pc,pct_hh_int
0,2010,Distrito Federal,5,1,0012,0,4312,212.0,370.0,2.26,8.37,8.13,1658.0,537.0,3214.0,1124,1083.0,1119.0,1078.0,5.0,3.99,598.0,314.0,284.0,182.0,4.916512,8.580705,32.388420,96.352313,99.55516,99.538319,0.44484,28.993536,26.223453,16.805171
1,2010,Distrito Federal,5,1,0012,1,174,9.0,13.0,2.12,8.92,8.67,67.0,23.0,128.0,43,NaN,NaN,NaN,NaN,4.05,26.0,15.0,12.0,6.0,5.172414,7.471264,34.328358,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,Distrito Federal,5,1,0012,2,167,5.0,13.0,1.82,8.83,8.49,66.0,20.0,105.0,44,NaN,NaN,NaN,NaN,3.80,23.0,12.0,7.0,5.0,2.994012,7.784431,30.303030,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,Distrito Federal,5,1,0012,3,153,8.0,9.0,2.00,8.77,8.78,60.0,19.0,119.0,40,NaN,NaN,NaN,NaN,3.83,21.0,17.0,13.0,11.0,5.228758,5.882353,31.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,Distrito Federal,5,1,0012,4,128,7.0,12.0,2.47,8.02,7.75,47.0,18.0,101.0,35,NaN,NaN,NaN,NaN,3.76,19.0,8.0,8.0,6.0,5.468750,9.375000,38.297872,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
shiny_df.to_csv("./GM_10_20.csv")