In [1]:
import pandas as pd
import numpy as np

In [2]:
def convert_dtype(x):
    if not x:
        return ''
    try:
        return str(x)   
    except:        
        return ''

data = pd.read_csv('BJClean_data.csv',converters={'POCUPADA_M': convert_dtype,'PRES2005': convert_dtype,
                                                  'PRES2005_F': convert_dtype, 'PRES2005_M': convert_dtype, 
                                                  'PRESOE05': convert_dtype, 'PRESOE05_F': convert_dtype, 
                                                  'TOTHOG': convert_dtype})
data

/Users/rafa/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (106,153) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,Tiempo,AGEB,GRAPROES,GRAPROES_F,GRAPROES_M,HOGJEF_F,HOGJEF_M,LOC,MUN,...,VPH_SNBIEN,VPH_S_ELEC,VPH_TELEF,VPH_TV,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M
0,2,2010,0011,13.80,13.31,14.37,570,873,1,14,...,*,0,1198,1373,NaN,NaN,NaN,NaN,NaN,NaN
1,3,2010,0011,13.46,13.34,13.59,24,35,1,14,...,0,0,36,55,NaN,NaN,NaN,NaN,NaN,NaN
2,4,2010,0011,14.10,13.88,14.41,53,63,1,14,...,0,0,101,106,NaN,NaN,NaN,NaN,NaN,NaN
3,5,2010,0011,13.28,12.85,13.78,50,82,1,14,...,*,0,109,123,NaN,NaN,NaN,NaN,NaN,NaN
4,6,2010,0011,13.58,13.22,14.03,29,30,1,14,...,0,0,51,58,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4383,4626,2020,1024,15.24,14.51,16.27,16,14,1,14,...,0,0,26,30,66,39,27,*,0,*
4384,4627,2020,1024,12.76,12.65,12.87,22,46,1,14,...,0,0,56,65,166,78,88,7,4,3
4385,4628,2020,1024,13.93,13.82,14.06,6,17,1,14,...,0,0,19,22,74,42,32,4,0,4
4386,4629,2020,1024,14.1,13.85,14.51,20,20,1,14,...,0,0,35,38,116,68,48,3,*,*
4387,4630,2020,1024,13.67,13.12,14.73,18,18,1,14,...,0,0,34,36,91,58,33,*,*,0

In [3]:
data['MUN'].unique()

array([14])

In [4]:
chosen_df = data[['Tiempo','NOM_ENT', 'MUN', 'LOC', 'AGEB', 'MZA', 'POBTOT', 'P_0A2', 'P_60YMAS', 'PROM_HNV', 'GRAPROES', 
                  'GRAPROES_F', 'POCUPADA', 'POCUPADA_F', 'PDER_SS', 'VIVTOT', 'TVIVHAB', 'TVIVPAR', 'VIVPAR_HAB', 
                  'VIVPAR_UT', 'PROM_OCUP', 'VPH_2YMASD', 'VPH_AUTOM', 'VPH_PC', 'VPH_INTER']]
chosen_df.head()

,Tiempo,NOM_ENT,MUN,LOC,AGEB,MZA,POBTOT,P_0A2,P_60YMAS,PROM_HNV,...,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPAR_UT,PROM_OCUP,VPH_2YMASD,VPH_AUTOM,VPH_PC,VPH_INTER
0,2010,Distrito Federal,14,1,0011,0,3900,124,567,1.28,...,1852,1540,1755,1443,68,2.50,905,966,1081,987
1,2010,Distrito Federal,14,1,0011,1,121,*,18,1.25,...,67,*,*,*,*,2.05,13,27,33,25
2,2010,Distrito Federal,14,1,0011,2,280,8,54,1.27,...,129,*,*,*,*,2.41,82,77,82,80
3,2010,Distrito Federal,14,1,0011,3,322,6,60,1.52,...,150,*,*,*,*,2.44,67,79,91,80
4,2010,Distrito Federal,14,1,0011,4,147,*,23,1.27,...,63,*,*,*,*,2.49,44,42,43,39

In [5]:
steps = chosen_df.replace(to_replace='*', value='') # replacing '*' with ''
steps = steps.replace(to_replace='N/D', value='') # replacing 'N/D' with ''
steps.columns= steps.columns.str.lower() # change column names to lower case

steps.head()

,tiempo,nom_ent,mun,loc,ageb,mza,pobtot,p_0a2,p_60ymas,prom_hnv,...,vivtot,tvivhab,tvivpar,vivpar_hab,vivpar_ut,prom_ocup,vph_2ymasd,vph_autom,vph_pc,vph_inter
0,2010,Distrito Federal,14,1,0011,0,3900,124,567,1.28,...,1852,1540,1755,1443,68,2.50,905,966,1081,987
1,2010,Distrito Federal,14,1,0011,1,121,,18,1.25,...,67,,,,,2.05,13,27,33,25
2,2010,Distrito Federal,14,1,0011,2,280,8,54,1.27,...,129,,,,,2.41,82,77,82,80
3,2010,Distrito Federal,14,1,0011,3,322,6,60,1.52,...,150,,,,,2.44,67,79,91,80
4,2010,Distrito Federal,14,1,0011,4,147,,23,1.27,...,63,,,,,2.49,44,42,43,39

In [6]:
steps.dtypes

tiempo         int64
nom_ent       object
mun            int64
loc            int64
ageb          object
mza            int64
pobtot         int64
p_0a2         object
p_60ymas      object
prom_hnv      object
graproes      object
graproes_f    object
pocupada      object
pocupada_f    object
pder_ss       object
vivtot         int64
tvivhab       object
tvivpar       object
vivpar_hab    object
vivpar_ut     object
prom_ocup     object
vph_2ymasd    object
vph_autom     object
vph_pc        object
vph_inter     object
dtype: object

In [7]:
cols=[i for i in steps.columns if i not in ["nom_ent","ageb"]] # change data frame dtypes to do math
for col in cols:
    steps[col]=pd.to_numeric(steps[col])

steps.dtypes

tiempo          int64
nom_ent        object
mun             int64
loc             int64
ageb           object
mza             int64
pobtot          int64
p_0a2         float64
p_60ymas      float64
prom_hnv      float64
graproes      float64
graproes_f    float64
pocupada      float64
pocupada_f    float64
pder_ss       float64
vivtot          int64
tvivhab       float64
tvivpar       float64
vivpar_hab    float64
vivpar_ut     float64
prom_ocup     float64
vph_2ymasd    float64
vph_autom     float64
vph_pc        float64
vph_inter     float64
dtype: object

In [8]:
# steps.columns = ['Entity', 'Municipality', 'Location', 'AGEB', 'Block', 'Total Pop.', 'Pop. 0-2', 'Pop. 60+', 
#                  'Avg. Offspring', 'Avg. Schooling', 'Avg. Female Sch.', 'Working Pop.', 'Working Female Pop.', 
#                  'Pop. Entitled to health services', 'Total Households', 'Inhabited HH.', 'Private HH.', 
#                  'Inhabited Pvt. HH.', 'Temporary Pvt. HH.', 'Avg. Occupants.', '2+ Bedrooms', 'HH. With Car', 'HH. With PC', 
#                  'HH. With Internet']

pd.options.display.max_columns = None # to show all columns
pd.options.display.max_rows = None

steps.head() # Name changing

,tiempo,nom_ent,mun,loc,ageb,mza,pobtot,p_0a2,p_60ymas,prom_hnv,graproes,graproes_f,pocupada,pocupada_f,pder_ss,vivtot,tvivhab,tvivpar,vivpar_hab,vivpar_ut,prom_ocup,vph_2ymasd,vph_autom,vph_pc,vph_inter
0,2010,Distrito Federal,14,1,0011,0,3900,124.0,567.0,1.28,13.80,13.31,1942.0,898.0,2664.0,1852,1540.0,1755.0,1443.0,68.0,2.50,905.0,966.0,1081.0,987.0
1,2010,Distrito Federal,14,1,0011,1,121,NaN,18.0,1.25,13.46,13.34,72.0,32.0,82.0,67,NaN,NaN,NaN,NaN,2.05,13.0,27.0,33.0,25.0
2,2010,Distrito Federal,14,1,0011,2,280,8.0,54.0,1.27,14.10,13.88,136.0,66.0,219.0,129,NaN,NaN,NaN,NaN,2.41,82.0,77.0,82.0,80.0
3,2010,Distrito Federal,14,1,0011,3,322,6.0,60.0,1.52,13.28,12.85,175.0,83.0,228.0,150,NaN,NaN,NaN,NaN,2.44,67.0,79.0,91.0,80.0
4,2010,Distrito Federal,14,1,0011,4,147,NaN,23.0,1.27,13.58,13.22,79.0,40.0,98.0,63,NaN,NaN,NaN,NaN,2.49,44.0,42.0,43.0,39.0

In [9]:
list(steps)

['tiempo',
 'nom_ent',
 'mun',
 'loc',
 'ageb',
 'mza',
 'pobtot',
 'p_0a2',
 'p_60ymas',
 'prom_hnv',
 'graproes',
 'graproes_f',
 'pocupada',
 'pocupada_f',
 'pder_ss',
 'vivtot',
 'tvivhab',
 'tvivpar',
 'vivpar_hab',
 'vivpar_ut',
 'prom_ocup',
 'vph_2ymasd',
 'vph_autom',
 'vph_pc',
 'vph_inter']

In [10]:
# Percents 

pop02_pct = steps['p_0a2']/steps['pobtot']*100

steps['pct_0a2'] = pop02_pct

pop60_pct = steps['p_60ymas']/steps['pobtot']*100
steps['pct_60'] = pop60_pct

working_fem_pct = steps['pocupada_f']/steps['pocupada']*100

steps['pct_wf'] = working_fem_pct

inhabited_hh_pct = steps['tvivhab']/steps['vivtot']*100
steps['pct_t_inhab_hh'] = inhabited_hh_pct

private_hh_pct = steps['tvivpar']/steps['vivtot']*100
steps['pct_privhh'] = private_hh_pct

inhabited_pvt_hh_pct = steps['vivpar_hab']/steps['vivtot']*100
steps['pct_privhh_inhab'] = inhabited_pvt_hh_pct

temp_pvt_hh_pct = steps['vivpar_ut']/steps['vivtot']*100
steps['pct_hhtemp'] = temp_pvt_hh_pct

hh_with_car = steps['vph_autom']/steps['vivtot']*100
steps['pct_hh_car'] = hh_with_car

hh_with_pc = steps['vph_pc']/steps['vivtot']*100
steps['pct_hh_pc'] = hh_with_pc

hh_with_int = steps['vph_inter']/steps['vivtot']*100
steps['pct_hh_int'] = hh_with_int

shiny_df = steps
shiny_df.head()

,tiempo,nom_ent,mun,loc,ageb,mza,pobtot,p_0a2,p_60ymas,prom_hnv,graproes,graproes_f,pocupada,pocupada_f,pder_ss,vivtot,tvivhab,tvivpar,vivpar_hab,vivpar_ut,prom_ocup,vph_2ymasd,vph_autom,vph_pc,vph_inter,pct_0a2,pct_60,pct_wf,pct_t_inhab_hh,pct_privhh,pct_privhh_inhab,pct_hhtemp,pct_hh_car,pct_hh_pc,pct_hh_int
0,2010,Distrito Federal,14,1,0011,0,3900,124.0,567.0,1.28,13.80,13.31,1942.0,898.0,2664.0,1852,1540.0,1755.0,1443.0,68.0,2.50,905.0,966.0,1081.0,987.0,3.179487,14.538462,46.240989,83.153348,94.762419,77.915767,3.671706,52.159827,58.369330,53.293737
1,2010,Distrito Federal,14,1,0011,1,121,NaN,18.0,1.25,13.46,13.34,72.0,32.0,82.0,67,NaN,NaN,NaN,NaN,2.05,13.0,27.0,33.0,25.0,NaN,14.876033,44.444444,NaN,NaN,NaN,NaN,40.298507,49.253731,37.313433
2,2010,Distrito Federal,14,1,0011,2,280,8.0,54.0,1.27,14.10,13.88,136.0,66.0,219.0,129,NaN,NaN,NaN,NaN,2.41,82.0,77.0,82.0,80.0,2.857143,19.285714,48.529412,NaN,NaN,NaN,NaN,59.689922,63.565891,62.015504
3,2010,Distrito Federal,14,1,0011,3,322,6.0,60.0,1.52,13.28,12.85,175.0,83.0,228.0,150,NaN,NaN,NaN,NaN,2.44,67.0,79.0,91.0,80.0,1.863354,18.633540,47.428571,NaN,NaN,NaN,NaN,52.666667,60.666667,53.333333
4,2010,Distrito Federal,14,1,0011,4,147,NaN,23.0,1.27,13.58,13.22,79.0,40.0,98.0,63,NaN,NaN,NaN,NaN,2.49,44.0,42.0,43.0,39.0,NaN,15.646259,50.632911,NaN,NaN,NaN,NaN,66.666667,68.253968,61.904762

In [11]:
shiny_df.to_csv("./BJ_10_20.csv")